dist: xenial  # required for Python >= 3.7
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
install:
  python setup.py install
script:
  python -m doctest -v README.rst
notifications:
  email:
    - filippo.valsorda@gmail.com
